"""add rooms and locations tables

Revision ID: 88a85adc70ca
Revises: c087b4b2c700
Create Date: 2025-04-30 19:21:35.573670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88a85adc70ca'
down_revision: Union[str, None] = 'c087b4b2c700'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.CheckConstraint('LENGTH(address) >= 5', name='check_location_address_length_ge_5'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address')
    )
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('image', sa.String(length=1000), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('LENGTH(description) >= 5', name='check_room_description_length_ge_1'),
    sa.CheckConstraint('capacity >= 1', name='check_room_capacity_ge_1'),
    sa.CheckConstraint('number >= 1', name='check_room_number_ge_1'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rooms')
    op.drop_table('locations')
    # ### end Alembic commands ###
