"""add is_notidied field to bookings model

Revision ID: c36cea8c50bf
Revises: 6300c76b2aae
Create Date: 2025-06-08 14:40:15.750530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c36cea8c50bf'
down_revision: Union[str, None] = '6300c76b2aae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('is_notified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'is_notified')
    # ### end Alembic commands ###
